name: Build & Test Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend 

      - name: Build Backend
        run: dotnet build --configuration Release ./backend

      - name: Run Backend Tests
        run: dotnet test --configuration Release --verbosity normal ./DbProvider.Tests

  frontend:
    name: Build & Test Angular Frontend
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Angular Project
        run: ng build --configuration=production
        working-directory: ./frontend
